# Generated by Django 5.2.5 on 2025-09-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(editable=False, max_length=60)),
                ('description', models.TextField(max_length=500)),
                ('images', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=500)),
                ('calories', models.PositiveIntegerField()),
            ],
        ),
    ]
