# Generated by Django 5.2.5 on 2025-10-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0003_alter_food_images_alter_food_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
