# Generated by Django 5.2.5 on 2025-10-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0004_food_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='images',
        ),
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
    ]
