# Generated by Django 5.2.5 on 2025-10-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0005_remove_food_images_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
