# Generated by Django 5.2.5 on 2025-10-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(default='strong and reliable car for everyday use'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(max_length=100),
        ),
    ]
